# Generated by Django 3.2 on 2023-06-16 02:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizado')),
                ('activity', models.CharField(choices=[('EXAMEN', 'Examen'), ('EXPOSICION', 'Exposición'), ('LECTURA', 'Lectura'), ('PARTICIPACION_CLASE', 'Participación en Clase'), ('TAREA', 'Tarea')], max_length=100, verbose_name='Tipo de actividad')),
                ('rating_number', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Calificación numérica')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_activity_rating', to='students.student', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_activity_rating', to='subjects.subject', verbose_name='Asignatura')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_activity_rating', to='teachers.teacher', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
