# Generated by Django 3.2 on 2023-06-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0002_auto_20230618_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_subject', to='students.Student', verbose_name='Estudiantes'),
        ),
    ]
